version: '3.8'

services:
  db:
    container_name: test_db
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5556:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 